categories:
  - title: 'Breaking Changes'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Doc Updates'
    label: 'doc'

template: |
  ## Changes

  $CHANGES
