version: '3'

services:
  db:
    image: postgres:12.0-alpine
    ports:
      - "5432:5432"
    env_file:
    - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=smartguard

volumes:
  postgres_data:
