name: Release Drafter

on:
  push:
    branches:
      - master
      - fix-semantic-release-action
jobs:
  release_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
